### ISSUE TITLE
Stopping the list of actions during the loop will cause the loop to start directly the next time it executes, requiring the keyword "break;"

### ISSUE THREAD

**Issue by Eruru3510** [ItsDeltin/Overwatch-Script-To-Workshop#34]
Problem Code:
![image](https://user-images.githubusercontent.com/35144004/61532643-07242300-aa5d-11e9-9cee-2024d62b8f69.png)

OW Code:
![image](https://user-images.githubusercontent.com/35144004/61532664-202cd400-aa5d-11e9-9957-2c68ab718085.png)

Describe:
The value of variable "i" will be set to "0" after the loop is completed. The code in front of the loop body will be executed the next time the rule is executed. If the action list is stopped during the loop, the value of variable "i" will not be set to "0", and the code in front of the loop body will not be executed the next time the rule is executed.

Solution Code:
![image](https://user-images.githubusercontent.com/35144004/61533232-d644ed80-aa5e-11e9-8f82-339277732563.png)

OW Code:
![image](https://user-images.githubusercontent.com/35144004/61533220-c88f6800-aa5e-11e9-90c8-11f68e3fdb80.png)

Describe:
Use "break;" to jump out of the loop immediately and set the value of the variable "i" to "0", so that the code in front of the loop will also be executed the next time the rule is executed.
Maybe you can also let "return;" work together, and when "return;" is executed in a loop, the value of the variable "i" is set to "0" by the way.

**Comment by ItsDeltin** [comment]
[v0.3.12](https://github.com/ItsDeltin/Overwatch-Script-To-Workshop/releases/tag/v0.3.12) will warn users about using `Abort()`, `AbortIf()`, `Skip()`, and `SkipIf()`.

I is set to 0 before the loop runs. The variable that is set to 0 is what determines how many actions to skip to return to the start of the for loop after a loop completes. This does not get reset if `Abort()` is ran.

A fix could be using a temp variable for the skip count. This will require 2 variables in the variable array and 5-6 actions instead of 1 variable and 2 actions.

**Comment by ItsDeltin** [comment]
[v0.3.13](https://github.com/ItsDeltin/Overwatch-Script-To-Workshop/releases/tag/v0.3.13) fixed aborting in loops. No break keyword yet.

**Comment by ItsDeltin** [comment]
Added `continue` and `break` in [v1.2](https://github.com/ItsDeltin/Overwatch-Script-To-Workshop/releases/tag/v1.2).
